# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
