# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170410_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
