# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
    ]
