# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_investment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='time_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
